[build]
  command = "bash build.sh"
  publish = "_output"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  RUBY_VERSION = "3.3.0"
  TZ = "America/Chicago"
  # Force Netlify to NOT use Hugo
  DISABLE_AUTO_INSTALL = "true"

[[redirects]]
  from = "http://jeremylongshore.com/*"
  to = "https://jeremylongshore.com/:splat"
  status = 301
  force = true

# Force rebuild Wed Oct 30 04:58:00 CDT 2025
